# Generated by Django 4.1.5 on 2023-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_language_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
