# Generated by Django 4.1.5 on 2023-02-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='name',
        ),
    ]
