# Generated by Django 4.1.5 on 2023-02-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_question_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='lesson',
        ),
    ]
