# Generated by Django 4.1.5 on 2023-02-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_quizzes_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lesson'),
        ),
    ]
