# Generated by Django 4.1.5 on 2023-02-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_quizzes_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
