# Generated by Django 3.2.7 on 2023-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_comment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
