# Generated by Django 4.2 on 2023-05-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
