# Generated by Django 4.1.6 on 2023-05-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_quizzes_total_attemps_result_attempt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizzes",
            old_name="total_attemps",
            new_name="total_attempts",
        ),
    ]
