# Generated by Django 4.1.6 on 2023-05-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0032_rename_total_attemps_quizzes_total_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(default="", max_length=50)),
                ("Last_Name", models.CharField(default="", max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                ("status", models.BooleanField(default=False)),
                ("role", models.IntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(default="", max_length=50)),
                ("Last_Name", models.CharField(default="", max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                ("status", models.BooleanField(default=False)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Fresher", "Fresher"),
                            ("Middle", "Middle"),
                            ("Senior", "Senior"),
                        ],
                        max_length=50,
                    ),
                ),
                ("role", models.IntegerField(default=0)),
                ("cv", models.FileField(upload_to="Media/authorCV")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
