# Generated by Django 4.1.6 on 2023-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_learner_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizzes",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
