# Generated by Django 4.1.6 on 2023-05-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_lesson_status_quizzes_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
