# Generated by Django 4.1.6 on 2023-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_video_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="role",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="learner",
            name="role",
            field=models.IntegerField(default=0),
        ),
    ]
