# Generated by Django 4.1.6 on 2023-06-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_video_slug_alter_instructor_role_alter_learner_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="certificate",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO")], max_length=100, null=True
            ),
        ),
    ]
