# Generated by Django 4.1.6 on 2023-06-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_course_featured_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learner",
            name="phone",
        ),
    ]
