# Generated by Django 4.1.6 on 2023-06-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_remove_learner_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor",
            name="phone",
        ),
    ]
