# Generated by Django 4.1.6 on 2023-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_remove_instructor_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("Learner", "Learner"), ("Instructor", "Instructor")],
                max_length=100,
            ),
        ),
    ]
