# Generated by Django 4.1.6 on 2023-06-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_alter_role_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="role",
            field=models.CharField(default="Instructor", max_length=10),
        ),
        migrations.AlterField(
            model_name="learner",
            name="role",
            field=models.CharField(default="Learner", max_length=7),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("Learner", "Learner"), ("Instructor", "Instructor")],
                max_length=10,
            ),
        ),
    ]
