# Generated by Django 4.1.6 on 2023-06-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_instructor_role_alter_learner_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="role",
            field=models.ForeignKey(
                default="Instructor",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.role",
            ),
        ),
    ]
