# Generated by Django 4.1.6 on 2023-06-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_instructor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="role",
            field=models.ForeignKey(
                default="Learner",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.role",
            ),
        ),
    ]
