# Generated by Django 4.1.6 on 2023-06-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_remove_course_certificate_course_has_certificate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
