# Generated by Django 4.2.3 on 2023-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_rename_course_room_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="name",
            new_name="course",
        ),
    ]
