# Generated by Django 4.2.3 on 2023-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_rename_name_room_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="Room", max_length=200),
        ),
    ]
