# Generated by Django 4.2.3 on 2023-07-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_alter_room_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="course",
        ),
        migrations.RemoveField(
            model_name="room",
            name="host",
        ),
        migrations.RemoveField(
            model_name="room",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="userroom",
            name="room",
        ),
        migrations.RemoveField(
            model_name="userroom",
            name="user",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="UserRoom",
        ),
    ]
