# Generated by Django 4.2.3 on 2023-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_remove_room_course_remove_room_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("FREE", "FREE"), ("PAID", "PAID")],
                default="FREE",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
