# Generated by Django 4.2.3 on 2023-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_video_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to="ProtectedVideoLectures"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
