# Generated by Django 4.2.4 on 2023-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_instructor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=25),
        ),
    ]
