# Generated by Django 4.2.4 on 2023-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_rename_status_payment_is_paid_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='avatar',
            field=models.ImageField(default='Media/avatar/default_avatar.png', upload_to='Media/avatar'),
        ),
    ]
