# Generated by Django 4.2.4 on 2023-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_instructor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=50),
        ),
    ]
