# Generated by Django 4.2.4 on 2023-08-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_instructor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('AI Engineer', 'AI Engineer'), ('Data Scientist', 'Data Scientist'), ('IOS Developer', 'IOS Developer'), ('Android Developer', 'Android Developer'), ('UI/UX Designer', 'UI/UX Designer')], default='', max_length=50),
        ),
    ]
